<?php

namespace MCQ\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * McqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class McqRepository extends EntityRepository
{
}
